# Generated by Django 5.2.2 on 2025-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(upload_to='journal/avatar'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='pdf',
            field=models.FileField(upload_to='journal/pdf'),
        ),
    ]
