# Generated by Django 5.2.2 on 2025-06-07 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_image_alter_journal_pdf'),
        ('paper', '0001_initial'),
        ('review', '0002_review_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_journal', to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='review',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_moderations', to='paper.paper'),
        ),
    ]
