# Generated by Django 5.2.2 on 2025-06-07 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper', '0001_initial'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(default=0)),
                ('commit', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper.paper')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_review', to='review.review')),
            ],
            options={
                'db_table': 'moderation',
            },
        ),
    ]
