# Generated by Django 5.2.2 on 2025-06-11 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderation',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='moderation',
            name='moder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_moder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
