# Generated by Django 5.2.2 on 2025-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_remove_moderation_reviewer_moderation_moder'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='is_verified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
